### ISSUE TITLE
Question: Why is `_queries` in `QueryCollection` private?

### ISSUE THREAD

**Issue by realjanpaulus** [snapADDY/databank#10]
I would like to execute all queries of my `QueryCollection` like in the following example:

```python
create_queries = QueryCollection.from_file("src/queries/create.sql")
for _, query in create_queries._queries.items():
    db.execute(query)
```

Does `_queries` has to be private? If not, one could access it directly (although it is obviously also now possible to do this, but not recommend because it is private :wink: ) and looping over it.
Alternatively, one could add the following getter function:

```python
def get_queries(self):
    return self._queries
```

**Comment by severinsimmler** [comment]
Good point. I'd suggest to make `QueryCollection` inherit from `collections.abc.Mapping` that you can do something like:

```python
queries = QueryCollection.from_file("queries.sql")
for key, query in queries.items():
    db.execute(query)
```
