### ISSUE TITLE
Bug: Only one newline allowed between statements in `.sql` file

### ISSUE THREAD

**Issue by realjanpaulus** [snapADDY/databank#12]
If a `.sql` file has more than one newline between each statement, one gets the following error:

```sh 
databank.query.InvalidQueryHeader: '' is not a valid query header
```

### Example

```sql
/* @name create_album */
CREATE TABLE IF NOT EXISTS album (
  ...
);



/* @name create_review */
CREATE TABLE IF NOT EXISTS review (
    ...
);
```

### Solution ideas

- Allow more than one newline in `.sql` files
- Autoformat loaded `.sql` file before further processing
- Document this rule

**Comment by severinsimmler** [comment]
Generally speaking I'd like to be relatively strict here, but I'll extend it to handle more than two `\n\n` to separate queries 👍
